---
- name: "Set up JBoss EAP"
  hosts: jboss
  gather_facts: "{{ gather_facts_override | default('true') }}"
  vars:
    jboss_home: "{{ jboss_home_override | default(lookup('env','JBOSS_HOME')) }}"
    java_home: "{{ java_home_override | default(lookup('env', 'JAVA_HOME')) }}"
    app_version: "{{ app_version_override | default('1.0') }}"
  collections:
    - wildfly.jcliff
  roles:
    - setup-jboss-eap
    - setup-pgsql-driver
    - jcliff
  tasks:
    - name: "Block"
      include_tasks: tasks/jcliff.yml
      loop:
        - 1
        - 2

- name: "Check compliance of EAP setup with Common Criteria"
  hosts: jboss
  gather_facts: "{{ gather_facts_override | default('true') }}"
  vars:
    jboss_home: "{{ jboss_home_override | default(lookup('env','JBOSS_HOME')) }}"
    java_home: "{{ java_home_override | default(lookup('env', 'JAVA_HOME')) }}"
    jdk_id: openjdk
    java_version: "1.8"
    jboss_server_service:
      script: "/usr/lib/systemd/system/jbossas.service"
      type: "SystemD"
      mode: "standalone"
  roles:
    - eap_common_criteria
