---
- name: "Set up JBoss EAP"
  hosts: jboss
  gather_facts: "{{ gather_facts_override | default('true') }}"
  vars:
    jboss_home: "{{ jboss_home_override | default(lookup('env','JBOSS_HOME')) }}"
    java_home: "{{ java_home_override | default(lookup('env', 'JAVA_HOME')) }}"
  collections:
    - wildfly.jcliff
  roles:
    - setup-jboss-eap
    - setup-pgsql-driver
    - jcliff
  tasks:
    - jcliff:
        wfly_home: "{{ jboss_home }}"
        timeout: 5000000
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: "enabled.plus"
          - drivers:
              - driver_name: postgresql
                driver_module_name: org.postgresql
                driver_class_name: org.postgresql.Driver
                driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
          - interfaces:
              - name: internal
                inet_address: '127.0.0.1'
              - name: public
                inet_address: '127.0.0.1'

    - name: "Configure protocols and associated interfaces"
      include_tasks: tasks/jcliff.yml


    - name: "Restart server"
      service:
        name: 'jbossas'
        state: restarted
      changed_when: false

- name: "Check compliance of EAP setup with Common Criteria"
  hosts: jboss
  gather_facts: "{{ gather_facts_override | default('true') }}"
  vars:
    jboss_home: "{{ jboss_home_override | default(lookup('env','JBOSS_HOME')) }}"
    java_home: "{{ java_home_override | default(lookup('env', 'JAVA_HOME')) }}"
    jdk_id: openjdk 
    java_version: "1.8"
    jboss_server_service:
      script: "/usr/lib/systemd/system/jbossas.service"
      type: "SystemD"
      mode: "standalone"
  roles:
    - eap_common_criteria
