- jcliff:
    wfly_home: "{{ jboss_home }}"
    timeout: 5000000
    subsystems:
     - standard_sockets:
         socket_binding:
           - name: "{{ item.name }}"
             interface: "{{ item.interface }}"
             port: "{{ item.port }}"
  loop:
    - name: ajp 
      interface: internal
      port: '8009'
    - name: http
      interface: public
      port: '8080'
    - name: https
      interface: public
      port: '8443'
    - name: management-http
      interface: internal
      port: '9990'
    - name: management-https
      interface: internal
      port: '9993'
    - name: txn-recovery-environment
      interface: internal
      port: '4712'
    - name: txn-status-manager
      interface: internal
      port: '4713'
