- set_fact:
    app:
      name: simple-webapp
      download_dir: /tmp/
      remote_dir: http://people.redhat.com/~rpelisse/
      extension: war

- name: Download a demo app to deploy
  get_url:
    url: "{{ app.remote_dir }}/{{ app.name }}-{{ app_version }}.{{ app.extension }}"
    dest: "{{ app.download_dir }}"

- jcliff:
    wfly_home: "{{ jboss_home }}"
    timeout: 5000000
    subsystems:
      - system_props:
          - name: jcliff.enabled
            value: "enabled.plus"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - interfaces:
          - name: internal
            inet_address: '127.0.0.1'
          - name: public
            inet_address: '127.0.0.1'
      - deployments:
          - name: "{{ app.name }}-{{ app_version }}.war"
            path: "{{ app.download_dir }}/{{ app.name }}-{{ app_version }}.war"
            replace_name_regex: "{{  app.name }}-.*"
      - standard_sockets:
          socket_binding:
            - name: ajp
              interface: internal
              port: '8009'
            - name: http
              interface: public
              port: '8080'
            - name: https
              interface: public
              port: '8443'
            - name: management-http
              interface: internal
              port: '9990'
            - name: management-https
              interface: internal
              port: '9993'
            - name: txn-recovery-environment
              interface: internal
              port: '4712'
            - name: txn-status-manager
              interface: internal
              port: '4713'

- name: "Restart server"
  service:
    name: 'jbossas'
    state: restarted
  changed_when: false

- name: Wait for server to restart
  wait_for:
    timeout: 30
