- name: Check that drivers is allowed all driver names
  assert:
    that:
      - item is defined
      - item.result is defined 
      - item.result in jdbc_classnames.allowed or item.result in jdbc_classnames.warn
    fail_msg: "{{ item.result }} is not a compliant to Common Criteria JDBC driver"
    quiet: true

- name: Notify is driver is only tolerated
  debug:
    msg: "WARN {{ item.result }} is tolerated but not stricly complitant to Common Criteria"
  when: item.result in jdbc_classnames.warn
