---
- name: Ensure start script is in compliance with Common Criteria recommendations
  assert:
    that:
      - java_version is defined
      - jboss_server_service.script is defined
      - jboss_server_service.mode is defined 
      - jboss_server_service.mode in jbossas_mode 
      - jboss_server_service.type is defined
      - jboss_server_service.type in service_manager_types
    fail_msg: "Missing required parameters to check for compliance"
    quiet: true

- name: Verify that jboss_server_service_script is a valid path
  stat:
    path: "{{ jboss_server_service.script }}"
  register: path_to_jboss_server_service_script

- set_fact:
    line_pattern: "ExecStart"
  when: jboss_server_service.type == 'SystemD'

- set_fact:
    line_pattern: "TODO"
  when: jboss_server_service.type == 'InitD'

- name: "Analyse the jbossas service script used: {{ jboss_server_service.script }}"
  shell: >
    grep "{{ jboss_server_service.script }}" -e "{{ jboss_home }}/bin/{{ jboss_server_service.mode }}.sh" | grep -e "{{ line_pattern }}" -c 
  register: output
  changed_when: false
  when: 
    - path_to_jboss_server_service_script.stat.exists
    - not path_to_jboss_server_service_script.stat.isdir 
    - not path_to_jboss_server_service_script.stat.islnk

- name: Ensure the jbossas service script used is in compliance
  assert:
    that:
      - output.stdout_lines is defined
      - output.stdout_lines|length >= 1
    fail_msg: "Missing start script"
    quiet: true
