---
- name: Ensure required parameters is provided
  assert:
    that:
      - subsystem is defined
      - jboss_home is defined
    fail_msg: Required parameters are not defined
    quiet: true

- set_fact:
    subsystem_name: "{{ subsystem.address[0].subsystem  }}"

- name: "Ensure that {{ subsystem_name }} is recommended by Common Critera"
  assert:
    that:
      - subsystem_name in allowed_subsystems
    fail_msg: "Subsystem is not recommend by Common Criteria - consider disabling"
    quiet: true
