---
- name: Prepare
  hosts: all
  tasks:
    - name: "Ensures required packages are installed"
      yum:
        name:
          - which
          - zip
          - unzip
          - procps-ng
          - initscripts
          - "{{ jvm_package | default('java-1.8.0-openjdk-devel') }}"
        state: present

    - name: "Ensures workdir '{{ workdir }}' is created"
      file:
        path: "{{ workdir }}"
        state: directory

    - name: "Ensure Wildfly user {{ jboss.user }} exists"
      user:
        name: "{{ jboss.user }}"
        comment: "User to run Wildfly"

    - name: "Download and unzip Wildfly zipfile from {{ wfly_download_url }}"
      unarchive:
        src: "{{ wfly_download_url }}"
        dest: "{{ workdir }}"
        owner: "{{ jboss.user }}"
        group: "{{ jboss.user }}"
        remote_src: yes
        creates: "{{ jboss_home_override }}"
