---
name: CI
"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7"]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/wildfly/jcliff

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule[docker]==3.0.2' ansible

      - name: Download Collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml
      - name: Run molecule test
        run: molecule test
